title:              HacktoberFest at Women Who Code
nav_title:          Home
email:              fellows@womenwhocode.com
description:        Your Journey towards Open Source
author:             Women Who Code
baseurl:            "/hacktoberfest21"
url:                ""

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-toc
  - jemoji
