title:              HacktoberFest at Women Who Code
email:              your-email@example.com
description:        Your Journey towards Open Source
author:             Women Who Code
baseurl:            "/hacktoberfest21"
url:                ""

# Social Profiles
twitter_username:   WomenWhoCode
github_username:    WomenWhoCode
facebook_username:  womenwhocode
instagram_username: womenwhocode
linkedin_username:  women-who-code

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
